# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Foresight' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foresight
  pod 'Charts'
  pod 'AloeStackView'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  
  target 'ForesightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ForesightUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
